export interface SettingsFormValues {
  phone: string;
  email: string;
  currency: string;
  is_logo: boolean;
  send_welcome_message: boolean;
  is_header: boolean;
  print_direct: boolean;
  barcode: boolean;
  show_water_mark: boolean;
  disable_doctor_service_check: boolean;
  send_result_after_auth: boolean;
  send_result_after_result: boolean;
  edit_result_after_auth: boolean;
  hospital_name: string | null;
  lab_name: string | null;
  address: string | null;
  vatin: string | null;
  cr: string | null;
  logo_file: File | null;
  clear_logo_base64: boolean;
  financial_year_start: string | null;
  financial_year_end: string | null;
  welcome_message: string | null;
  header_content: string | null;
  header_image_file: File | null;
  clear_header_base64: boolean;
  inventory_notification_number: string | null;
  instance_id: string | null;
  token: string | null;
  finance_account_id: string | null;
  bank_id: string | null;
  company_account_id: string | null;
  endurance_account_id: string | null;
  main_cash: string | null;
  main_bank: string | null;
  pharmacy_cash: string | null;
  pharmacy_bank: string | null;
  pharmacy_income: string | null;
  auditor_stamp_file: File | null;
  clear_auditor_stamp: boolean;
  manager_stamp_file: File | null;
  clear_manager_stamp: boolean;
  report_header_company_name: string | null;
  report_header_address_line1: string | null;
  report_header_address_line2: string | null;
  report_header_phone: string | null;
  report_header_email: string | null;
  report_header_vatin: string | null;
  report_header_cr: string | null;
  report_header_logo_file: File | null;
  clear_report_header_logo_base64: boolean;
} 